### ISSUE TITLE
Describing environments is outdated

### ISSUE THREAD

**Issue by chadwcarlson** [platformsh-templates/strapi4#31]
### Describe the bug

All environments run in production, but the README still describes the previous configuration - where development environments ran development servers so that Content Types were editable at runtime. 

This is no longer the case, and the `.platform.app.yaml` description [here](https://github.com/platformsh-templates/strapi4/blob/master/README.md#customizations) needs to be updated. 

### Include some logs

no logs

### Reproducing

Just readme updates

### Expected behavior

Code reflects production start on all environments

### Your environment

Readme makes user expect dev environments are available

### Additional context

@hacktivist123

**Comment by hacktivist123** [comment]
To understand you, all environments created are run in production and content type can be created at runtime regardless? @chadwcarlson
